Rewrite ci for PRs for gh-actions

diff --git a/.github/workflows/ci-pr.yml b/.github/workflows/ci-pr.yml
--- a/.github/workflows/ci-pr.yml
+++ b/.github/workflows/ci-pr.yml
@@ -1,176 +1,96 @@
-# Created on 2022-12-12 by converting .gitlab-ci.yaml with gh actions-importer
-# gh version 2.20.2, actions-importer v1.0.1, actions-importer/cli v1.0.14577
+# This action runs when a pull request to main is created or updated
+# (but not when it is merged).
+#
+# Workflow steps:
+# - run voc4cat to update xlsx file and create turtle file
+# - store artifacts (even on failure)
+# - check approval
+# - remove xlsx-vocab file from PR and commit
 
-name: nfdi4cat/ta1-ontologies/voc4cat-template
+name: CI on pull request create or update
 on:
-  push:
   pull_request:
+    branches: 
+      - main
+    types: [opened, edited, synchronize]
   workflow_dispatch:
-concurrency:
-  group: "${{ github.ref }}"
-  cancel-in-progress: true
+
 env:
-  PROJECT_ACCESS_TOKEN: "${{ secrets.PROJECT_ACCESS_TOKEN }}"
-  VOC4CAT_READ_TOKEN: "${{ secrets.VOC4CAT_READ_TOKEN }}"
+  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  FORCE_COLOR: "1"  # Make tools pretty.
+  PIP_DISABLE_PIP_VERSION_CHECK: "1"
+
 jobs:
+  if: ${{ github.event.pull_request.merged }}
   vocab_build:
+    # Run on all pull request types except merge which has its own workflow.
+    if: ${{ !github.event.pull_request.merged }}
     runs-on: ubuntu-latest
-    container:
-      image: python:3.10.8-bullseye
-    if: ${{ github.event_name }} == 'merge_request_event'
-    timeout-minutes: 60
-    env:
-      PIP_CACHE_DIR: "${{ github.workspace }}/.cache/pip"
+    timeout-minutes: 10
+
     steps:
-    - uses: actions/checkout@v2
+    - uses: actions/checkout@v3
+
+    - uses: actions/setup-python@v4
       with:
-        fetch-depth: 20
-        lfs: true
-    - uses: actions/cache@v3
+        python-version: '3.11'
+
+    - name: Install dependencies
+      run: |
+        python -VV
+        python -m pip install --upgrade pip setuptools wheel
+      # python -m pip install -U git+https://${{ github.event.repository.name }}:$VOC4CAT_READ_TOKEN@gitlab.fokus.fraunhofer.de/nfdi4cat/ta1-ontologies/voc4cat-tool.git@main
+        python -m pip pip install git+https://${GITHUB_PAT}@github.com/dalito/voc4cat-tool.git@main
+
+    - name: Run voc4cat
+      run: |
+        voc4cat --version
+        ls -l outbox/ || echo "outbox directory does not exist."
+        voc4cat --add_IRI --check --forward --docs --output-directory outbox inbox-excel-vocabs/ |& tee voc4cat.log || EXIT_CODE=${PIPESTATUS[0]}
+        mv voc4cat.log outbox
+        ls -l outbox/ || echo "outbox directory does not exist."
+        echo "${EXIT_CODE}"
+        if [ $EXIT_CODE -ne 0 ]; then exit ${EXIT_CODE}; fi;
+    
+    - name: Store artifacts
+      if: ${{ always() }}
+      uses: actions/upload-artifact@v3
       with:
-        path: |-
-          .cache/pip
-          .venv/
-        key: default
-    - run: python --version
-    - run: python -m venv .venv
-    - run: source .venv/bin/activate
-    - run: python -m pip install -U pip
-    - run: pip install -U git+https://${{ github.event.repository.name }}:$VOC4CAT_READ_TOKEN@gitlab.fokus.fraunhofer.de/nfdi4cat/ta1-ontologies/voc4cat-tool.git@main
-    - run: git config --global user.email "${{ github.actor }}"
-    - run: git config --global user.name "${{ github.actor }}"
-    - run: git fetch --tags
-    - run: git branch -v
-    - run: ls -l outbox/ || echo "outbox directory does not exist."
-    - run: voc4cat --version
-    - run: 'voc4cat --add_IRI --check --forward --docs --output-directory outbox inbox-excel-vocabs/ |& tee voc4cat.log || EXIT_CODE=${PIPESTATUS[0]}
-        '
-    - run: mv voc4cat.log outbox
-    - run: ls -l outbox/ || echo "outbox directory does not exist."
-    - run: echo "${EXIT_CODE}"
-    - run: if [ $EXIT_CODE -ne 0 ]; then exit ${EXIT_CODE}; fi;
-    - uses: actions/upload-artifact@v2
-      if: always()
-      with:
-        name: "${{ github.job }}"
+        name: voc4cat-outbox
         path: outbox/
-  vocab_commit:
-    needs: vocab_build
-    runs-on: ubuntu-latest
-    container:
-      image: python:3.10.8-bullseye
-    if: ${{ github.event_name }} == 'merge_request_event'
-    timeout-minutes: 60
-    env:
-      PIP_CACHE_DIR: "${{ github.workspace }}/.cache/pip"
-    steps:
-    - uses: actions/checkout@v2
+
+    - name: Merge changes into vocabulary
+      run: |
+        git status
+        merge_vocab outbox/ vocabularies/
+      # git add vocabularies/\*.ttl || echo "No ttl files to add."
+      # git status
+
+    - name: Commit vocabulary changes
+      uses: stefanzweifel/git-auto-commit-action@v4
       with:
-        fetch-depth: 20
-        lfs: true
-    - uses: actions/cache@v3
+        commit_message: 'CI: vocabulary update in pipeline $CI_PIPELINE_ID'
+        push: true
+        # glob pattern of files which should be added to the commit
+        file_pattern: 'vocabularies/\*.ttl'
+      run: |
+        git status
+
+    - name: Remove Excel vocabulary files from inbox
+      run: |
+        git rm inbox-excel-vocabs/\*.xlsx || echo "No xlsx files to remove."
+        git status
+
+    - name: Commit clean-up changes
+      # Pin third party action (v4.16.0)
+      # uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a
+      uses: stefanzweifel/git-auto-commit-action@v4
       with:
-        path: |-
-          .cache/pip
-          .venv/
-        key: default
-    - run: python --version
-    - run: python -m venv .venv
-    - run: source .venv/bin/activate
-    - run: python -m pip install -U pip
-    - run: pip install -U git+https://${{ github.event.repository.name }}:$VOC4CAT_READ_TOKEN@gitlab.fokus.fraunhofer.de/nfdi4cat/ta1-ontologies/voc4cat-tool.git@main
-    - run: git config --global user.email "${{ github.actor }}"
-    - run: git config --global user.name "${{ github.actor }}"
-    - run: git fetch --tags
-    - run: git branch -v
-    - run: git checkout ${{ github.event.pull_request.head.ref }}
-    - run: git status
-    - run: merge_vocab outbox/ vocabularies/
-    - run: git add vocabularies/\*.ttl || echo "No ttl files to add."
-    - run: git status
-    - run: git remote set-url origin "https://${{ github.event.repository.name }}:$PROJECT_ACCESS_TOKEN@${{ github.server_url }}/${{ github.repository }}.git"
-    - run: 'git commit -m "CI: vocabulary update in pipeline ${{ github.repository}}/${{ github.workflow }}" || echo "Nothing to commit"'
-    - run: echo "pushing to branch ${{ github.event.pull_request.head.ref }}"
-    - run: git push -o ci.skip origin HEAD:${{ github.event.pull_request.head.ref }}
-  vocab_clean:
-    needs: vocab_commit
-    runs-on: ubuntu-latest
-    container:
-      image: python:3.10.8-bullseye
-    if: ${{ github.event_name }} == 'merge_request_event'
-    timeout-minutes: 60
-    env:
-      PIP_CACHE_DIR: "${{ github.workspace }}/.cache/pip"
-    steps:
-    - uses: actions/checkout@v2
-      with:
-        fetch-depth: 20
-        lfs: true
-    - uses: actions/cache@v3
-      with:
-        path: |-
-          .cache/pip
-          .venv/
-        key: default
-    - run: python --version
-    - run: python -m venv .venv
-    - run: source .venv/bin/activate
-    - run: python -m pip install -U pip
-    - run: pip install -U git+https://${{ github.event.repository.name }}:$VOC4CAT_READ_TOKEN@gitlab.fokus.fraunhofer.de/nfdi4cat/ta1-ontologies/voc4cat-tool.git@main
-    - run: git config --global user.email "${{ github.actor }}"
-    - run: git config --global user.name "${{ github.actor }}"
-    - run: git fetch --tags
-    - run: git branch -v
-    - run: git config user.name "CI.runner"
-    - run: git config user.email "CI.runner@gitlab.fokus.fraunhofer.de"
-    - run: git checkout ${{ github.event.pull_request.head.ref }}
-    - run: git status
-    - run: git rm inbox-excel-vocabs/\*.xlsx || echo "No xlsx files to remove."
-    - run: git status
-    - run: git remote set-url origin "https://${{ github.event.repository.name }}:$PROJECT_ACCESS_TOKEN@${{ github.server_url }}/${{ github.repository }}.git"
-    - run: git remote -v
-    - run: 'git commit -m "CI: remove Excel files from inbox-excel-vocabs" || echo "Nothing to commit"'
-    - run: git push -o ci.skip origin HEAD:${{ github.event.pull_request.head.ref }}
-  vocab_publish:
-    needs:
-    - vocab_build
-    - vocab_commit
-    - vocab_clean
-    runs-on: ubuntu-latest
-    container:
-      image: python:3.10.8-bullseye
-    if: github.ref == 'refs/heads/main'
-    timeout-minutes: 60
-    env:
-      PIP_CACHE_DIR: "${{ github.workspace }}/.cache/pip"
-    steps:
-    - uses: actions/checkout@v2
-      with:
-        fetch-depth: 20
-        lfs: true
-    - uses: actions/cache@v3
-      with:
-        path: |-
-          .cache/pip
-          .venv/
-        key: default
-    - uses: actions/download-artifact@v2
-    - run: python --version
-    - run: python -m venv .venv
-    - run: source .venv/bin/activate
-    - run: python -m pip install -U pip
-    - run: pip install -U git+https://${{ github.event.repository.name }}:$VOC4CAT_READ_TOKEN@gitlab.fokus.fraunhofer.de/nfdi4cat/ta1-ontologies/voc4cat-tool.git@main
-    - run: git config --global user.email "${{ github.actor }}"
-    - run: git config --global user.name "${{ github.actor }}"
-    - run: git fetch --tags
-    - run: git branch -v
-    - run: voc4cat --version
-    - run: echo "Welcome to the partially implemented deploy pipeline."
-    - run: voc4cat --check --forward --docs --output-directory publish vocabularies/
-    - run: cp vocabularies/*.ttl publish/ || echo "no turtle(ttl) vocabulary files to publish."
-    - run: ls -l publish/ || echo "publish directory does not exist."
-    - uses: actions/upload-artifact@v2
-      if: success()
-      with:
-        name: "${{ github.job }}"
-        path: publish/
+        commit_user_name: voc4cat gh-actions bot
+        commit_user_email: voc4cat-bot@example.org
+        # commit_author: Author <actions@github.com> # needed?
+        commit_message: 'CI: Remove Excel files from inbox-excel-vocabs'
+        push: true
+
+# Lit:
+# https://github.com/stefanzweifel/git-auto-commit-action
